# .pre-commit-config.yaml
# ------------------------------------------------------------
# Стили кода + линтер без «pre-commit-hooks», чтобы не требовать
# интерактивный login в корпоративный Artifactory.
# ------------------------------------------------------------

repos:
  # ------------------------ BLACK ---------------------------
  - repo: https://github.com/psf/black
    rev: 24.3.0            # актуальная стабильная версия
    hooks:
      - id: black
        language_version: python3.12   # используем системный 3.12

  # ------------------------ ISORT ---------------------------
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        language_version: python3.12

  # ------------------------ FLAKE8 --------------------------
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3.12
        additional_dependencies:
          - flake8-bugbear            # усиленные правила
